apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-6n8k
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/rsoaresd_org/rhtap-demo-wkyu-tenant/rhtap-demo-app/hacbs-test-project-6n8k@sha256:1ca56618bbf6118e6d2bd5201e8932f1ec8244b1b86bd17cf1fa6956e3b338a6
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
