apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-6n8k
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-6n8k
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-6n8k
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-6n8k
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-6n8k
    spec:
      containers:
      - image: quay.io/rsoaresd_org/rhtap-demo-wkyu-tenant/rhtap-demo-app/hacbs-test-project-6n8k@sha256:0d9086a1290f49974e98467ad7b0e121d9e966d372c3708db89a103e444eb41f
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
